Repository taechoma-eul/YOLA, pull requests merged in 2025-04, with the labels that each got.

#12 add: @hookform/resolvers 추가
  package.json
  pnpm-lock.yaml
Labels: ⚙ Setting

#13 Feature/#5 checklist 체크리스트 메인화면 이동에 따른 중간PR
  src/app/(checklist)/checklist/.gitkeep
  src/app/(checklist)/checklist/[mission]/page.tsx
  src/app/page.tsx
  src/components/features/.gitkeep
  src/components/features/checklist/checklist-client.tsx
  src/lib/utils/api/checklist.api.ts
Labels: ✨ Feature, 📬 API, 🍋 예린

#14 Feature/#6 mypage 마이페이지 기본 UI 및 링크 기능 구현 _ 중간PR
  public/images/.gitkeep
  public/images/default-avatar.png
  public/images/sample-image.jpeg
  src/app/(auth)/mypage/achievement/.gitkeep
  src/app/(auth)/mypage/achievement/page.tsx
  src/app/(auth)/mypage/layout.tsx
  src/app/(auth)/mypage/my-gonggam-post-list/page.tsx
  src/app/(auth)/mypage/my-life-list/.gitkeep
  src/app/(auth)/mypage/my-life-list/page.tsx
  src/app/(auth)/mypage/profile/page.tsx
  src/components/features/mypage/mypage-sidebar.tsx
  src/components/ui/.gitkeep
  src/components/ui/life-post-card.tsx
  src/constants/page-path.ts
  src/lib/utils/api/my-life.api.ts
  src/types/life-post.ts
Labels: ✨ Feature, 🎨 HTML&CSS

#16 Feature/#3 로그인 회원가입 기능
  src/app/(auth)/(confirm)/route.ts
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/.gitkeep
  src/app/(auth)/signup/page.tsx
  src/app/middleware.ts
  src/app/page.tsx
  src/components/features/auth-form/auth-form-container.tsx
  src/components/features/auth-form/auth-form-input.tsx
  src/components/features/auth-form/form-button-box.tsx
  src/components/features/auth-form/login-form.tsx
  src/components/features/auth-form/signup-form.tsx
  src/constants/auth-form.ts
  src/lib/utils/.gitkeep
  src/lib/utils/api/auth-action.ts
  src/lib/utils/authValidate.ts
  src/lib/utils/supabase/middleware.ts
  src/types/.gitkeep
  src/types/children.ts
  src/types/components/auth-form.ts
Labels: ✨ Feature, 📬 API, 🌝 수임

#25 add:fullcalendar/interaction
  package.json
  pnpm-lock.yaml
Labels: ⚙ Setting

#26 Feature/#17 소셜 로그인
  src/app/api/auth/callback/route.ts
  src/components/features/auth-form/auth-form-container.tsx
  src/components/features/auth-form/form-button-box.tsx
  src/components/features/auth-form/login-form.tsx
  src/constants/page-path.ts
  src/lib/utils/api/auth-action.ts
Labels: ✨ Feature, 📬 API, 🌝 수임

#31 Feature/#29 루트 레이아웃 적용
  src/app/layout.tsx
  src/components/layout/footer/footer.tsx
  src/components/layout/header/header-dropdown-menu-item.tsx
  src/components/layout/header/header-dropdown-menu.tsx
  src/components/layout/header/header-guest-option.tsx
  src/components/layout/header/header-nav.tsx
  src/components/layout/header/header-user-option.tsx
  src/components/layout/header/header.tsx
  src/constants/page-path.ts
  src/lib/utils/api/auth-action.ts
  src/types/components/header.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 🌝 수임

#30 Feature/#5 checklist 혼자 체크리스트 기능 구현
  src/app/(checklist)/checklist/[mission]/page.tsx
  src/app/(checklist)/checklist/post/[...mission]/page.tsx
  src/components/features/checklist/post-mission-clear.tsx
  src/constants/magic-number.ts
  src/constants/page-path.ts
  src/lib/utils/api/checklist.api.ts
  src/lib/utils/user-mission.ts
  src/types/checklist.ts
Labels: ✨ Feature, 📬 API, 🍋 예린

#20 Feature/#19 ramdom mission modal 구현
  src/components/features/modals/random-mission.tsx
  src/constants/supabase-tables-name.ts
  src/lib/utils/api/mission-list.api.ts
Labels: ✨ Feature, 🐣 민주

#34 Setting/#33 supabase data type 파일 생성
  src/types/supabase.d.ts
Labels: ⚙ Setting, 🌝 수임

#38 Refactor/#37 폴더 구조 변경
  src/components/features/auth-form/auth-form-input.tsx
  src/components/features/auth-form/login-form.tsx
  src/components/features/auth-form/signup-form.tsx
  src/components/ui/alert.tsx
  src/components/ui/avatar.tsx
  src/components/ui/button.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/menubar.tsx
  src/components/ui/skeleton.tsx
  src/components/ui/textarea.tsx
  src/components/ui/toast.tsx
  src/lib/hooks/.gitkeep
  src/lib/hooks/mutations/.gitkeep
  src/lib/hooks/queries/.gitkeep
  src/lib/hooks/use-toast.ts
  src/lib/utils/utils.ts
  src/lib/utils/validation/authValidate.ts
  src/lib/utils/validation/life-record-schema.ts
  src/types/components/auth-form.ts
Labels: 🔨 Refactor, 🌝 수임

#40 Install/#39 tanstack query 버전 업그레이드
  package.json
  pnpm-lock.yaml
  src/lib/utils/supabase/supabase-client.ts
  src/lib/utils/supabase/supabase-server.ts
  src/types/supabase.d.ts
Labels: ⚙ Setting, 🌝 수임

#42 add: supabase cli set
  package.json
  pnpm-lock.yaml
  src/constants/auth-form.ts
  src/constants/supabase-tables-name.ts
  src/types/supabase.d.ts
Labels: ⚙ Setting, 🐈‍⬛ 선제

#36 Feature/#23 calendar db sync
  next.config.js
  next.config.mjs
  package.json
  src/app/(life)/life/page.tsx
  src/app/globals.css
  src/components/common/post-input-form.tsx
  src/components/features/life/calendar.tsx
  src/components/features/life/solo-life-card.tsx
  src/components/features/life/solo-life-list.tsx
  src/components/life/calendar.tsx
  src/components/life/solo-life-list.tsx
  src/lib/hooks/queries/useLifePostsByMonth.ts
  src/lib/hooks/use-user.ts
  src/lib/utils/api/life-api-client.ts
  src/lib/utils/api/my-life.api.ts
  src/types/life-post.ts
  src/types/solo-life.ts
Labels: ✨ Feature, 📬 API

#50 Install/#48 add heic convert
  package.json
  pnpm-lock.yaml
  src/types/heic-convert.d.ts
  tsconfig.json
Labels: ⚙ Setting, 🌝 수임

#53 Install/#51-add_react_swiper
  package.json
  pnpm-lock.yaml
Labels: ⚙ Setting, 🌝 수임

#56 Install/#54 UUID & date pick
  package.json
  pnpm-lock.yaml
  src/components/ui/calendar.tsx
  src/components/ui/popover.tsx
  src/types/supabase.d.ts
Labels: ⚙ Setting, 🐈‍⬛ 선제

#45 Feature/#6 mypage achievement 기본 UI 및 데이터 연동(다시 올려요!)
  src/app/(auth)/mypage/achievement/page.tsx
  src/components/features/mypage/button-client-component.tsx
  src/components/features/mypage/mypage-progressbar.tsx
  src/constants/supabase-tables-name.ts
  src/lib/utils/api/my-mission.api.ts
  src/lib/utils/calculate-user-level.ts
Labels: ✨ Feature, 📬 API, 🎨 HTML&CSS, 🥨 지은

#52 Refactor/#41 checklist 체크리스트 유저정보 표출 로직개선
  .gitignore
  src/app/(checklist)/checklist/[mission]/page.tsx
  src/constants/magic-number.ts
  src/constants/messages.ts
  src/constants/mission.ts
  src/lib/utils/api/checklist.api.ts
  src/lib/utils/user-mission.ts
  src/types/checklist.ts
  src/types/supabase.d.ts
Labels: ✨ Feature, 🔨 Refactor, 🍋 예린

#60 Feature/#55 calendar & input form edit
  src/app/(life)/life/page.tsx
  src/app/(life)/life/post/page.tsx
  src/components/common/date-picker.tsx
  src/components/common/life-post-card.tsx
  src/components/common/post-input-form.tsx
  src/components/common/solo-life-card.tsx
  src/components/features/life/solo-life-card.tsx
  src/components/features/life/solo-life-list.tsx
  src/lib/hooks/mutations/useLifePost.ts
  src/lib/hooks/queries/use-life-posts-by-month.ts
  src/lib/utils/api/life-api-client.ts
  src/lib/utils/utc-to-kst.ts
  src/types/life-post.ts
Labels: ✨ Feature

#58 Feature/#47 home page layout
  src/app/page.tsx
  src/components/features/home/main-banner-swiper.tsx
  src/components/features/home/main-checklist-card.tsx
  src/components/features/home/main-gonggam-item-container.tsx
  src/components/features/home/main-gonggam-item-contents-container.tsx
  src/components/features/home/main-gonggam-item-reaction-box.tsx
  src/components/features/home/main-gonggam-item.tsx
  src/components/features/home/main-gonggam-preview-container.tsx
  src/components/features/home/main-gonggam-preview-title-box.tsx
  src/components/features/home/main-gonggam-preview.tsx
  src/components/features/home/main-random-mission-box.tsx
  src/components/features/home/main-random-mission-container.tsx
  src/components/features/home/main-random-title-box.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, 🌝 수임

#70 Feature/#68 calendar UI fix
  src/app/(life)/life/page.tsx
  src/app/globals.css
  src/components/common/post-input-form.tsx
  src/components/features/life/calendar.tsx
  src/components/features/life/custom-header.tsx
  src/components/features/life/life-page-client.tsx
  src/lib/hooks/queries/use-life-posts-by-month-range.ts
  src/lib/utils/get-date.ts
  src/lib/utils/get-today.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 🐈‍⬛ 선제

#67 Feature/#44 마이페이지 (혼자라이프) 무한스크롤 구현
  package.json
  pnpm-lock.yaml
  src/app/(auth)/mypage/my-life-list/page.tsx
  src/components/features/mypage/my-life-list-client.tsx
  src/constants/default-image-url.ts
  src/constants/query-keys.ts
  src/lib/hooks/queries/use-get-life-posts-infinite-query.ts
  src/lib/utils/api/my-life-client.api.ts
  src/types/life-post.ts
Labels: ✨ Feature, 📬 API, 🎨 HTML&CSS, 🥨 지은

#71 Feature/#35 checklist post 미션인증 글 작성 기능구현
  src/app/(checklist)/checklist/[mission]/page.tsx
  src/app/(checklist)/checklist/post/[...mission]/page.tsx
  src/app/(life)/life/post/page.tsx
  src/app/layout.tsx
  src/components/common/post-input-form.tsx
  src/components/features/checklist/checklist-post-dropdown.tsx
  src/components/features/checklist/mission-list-client.tsx
  src/components/features/checklist/post-mission-clear.tsx
  src/components/ui/toaster.tsx
  src/constants/magic-number.ts
  src/constants/messages.ts
  src/lib/hooks/mutations/useLifePost.ts
  src/lib/utils/api/checklist-post.api.ts
  src/lib/utils/api/checklist.api.ts
Labels: ✨ Feature, 📬 API, 🍋 예린

#79 Feature/#74 gonggam board 공감게시판 - 메인페이지
  public/.gitkeep
  src/app/gonggam/(board)/[category]/layout.tsx
  src/app/gonggam/(board)/[category]/page.tsx
  src/app/gonggam/(post)/[category]/[postId]/layout.tsx
  src/app/gonggam/(post)/[category]/[postId]/page.tsx
  src/app/gonggam/page.tsx
  src/components/features/gonggam/gonggam-header.tsx
  src/components/features/gonggam/gonggam-pagination.tsx
  src/components/features/gonggam/gonggam-tabs-nav.tsx
  src/components/ui/pagination.tsx
  src/constants/gonggam-category.ts
  src/constants/page-path.ts
  src/lib/utils/api/gonggam-board.api.ts
  src/types/gonggam.ts
Labels: ✨ Feature, 📬 API, 🎨 HTML&CSS, 🍋 예린

#78 Refactor/#69 my achievement 코드 리팩토링 _ 중간PR
  public/images/clean-icon.svg
  public/images/goat-icon.svg
  public/images/meal-icon.svg
  public/images/play-icon.svg
  public/images/travel-icon.svg
  src/app/(auth)/mypage/achievement/page.tsx
  src/components/features/mypage/button-client-component.tsx
  src/components/features/mypage/my-life-list-client.tsx
  src/components/features/mypage/mypage-progressbar.tsx
  src/lib/utils/api/my-life-client.api.ts
  src/lib/utils/api/my-life.api.ts
  src/lib/utils/api/my-mission.api.ts
  src/lib/utils/calculate-user-level.ts
Labels: 🎨 HTML&CSS, 🔨 Refactor, 🥨 지은

#72 Feature/#22 calendar modal
  src/components/common/edit-delete-dropdown.tsx
  src/components/features/modals/calendar-post-detail.tsx
  src/components/ui/card-detail-image-swiper.tsx
  src/constants/query-keys.ts
  src/lib/hooks/mutations/use-delete-life-post.ts
Labels: ✨ Feature, 🐣 민주

#65 Feature/#59 main page + 인기순 글 정렬
  src/app/globals.css
  src/app/page.tsx
  src/components/features/home/main-checklist-card.tsx
  src/components/features/home/main-gonggam-item-container.tsx
  src/components/features/home/main-gonggam-item.tsx
  src/components/features/home/main-gonggam-preview-container.tsx
  src/components/features/home/main-gonggam-preview-title-box.tsx
  src/components/features/home/main-gonggam-preview.tsx
  src/components/features/home/main-random-mission-box.tsx
  src/components/layout/header/header-main-logo.svg.tsx
  src/lib/utils/api/gonggam-posts.api.ts
  src/types/gonggam-posts.ts
  src/types/supabase.d.ts
Labels: ✨ Feature, 📬 API, 🌝 수임

#81 Refactor/#66 auth system
  public/images/default-avatar.png
  public/images/default-avatar.svg
  src/app/(auth)/login/page.tsx
  src/app/(auth)/mypage/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/private/page.tsx
  src/components/common/profile-avatar.tsx
  src/components/features/auth-form/auth-form-container.tsx
  src/components/features/auth-form/auth-form-field.tsx
  src/components/features/auth-form/auth-form-input.tsx
  src/components/features/auth-form/auth-form.tsx
  src/components/features/auth-form/auth-page-ui.tsx
  src/components/features/auth-form/form-button-box.tsx
  src/components/features/auth-form/login-form-button.tsx
  src/components/features/auth-form/login-form.tsx
  src/components/features/auth-form/signup-form-button.tsx
  src/components/features/auth-form/signup-form.tsx
  src/components/features/mypage/edit-profile-form-email-field.tsx
  src/components/features/mypage/edit-profile-form-image-field.tsx
  src/components/features/mypage/edit-profile-form-nickname-field.tsx
  src/components/features/mypage/edit-profile-form.tsx
  src/components/features/mypage/mypage-sidebar-profile.tsx
  src/components/features/mypage/mypage-sidebar.tsx
  src/components/ui/form.tsx
  src/components/ui/toast.tsx
  src/constants/api-url.ts
  src/constants/auth-form.ts
  src/constants/default-image-url.ts
  src/lib/hooks/mutations/use-profile-update-mutate.ts
  src/lib/hooks/queries/use-get-user-profile.ts
  src/lib/hooks/use-auth-form.ts
  src/lib/hooks/use-profile-form.ts
  src/lib/utils/api/auth-action.ts
  src/lib/utils/supabase/middleware.ts
  src/lib/utils/toast.ts
  src/lib/utils/validation/auth-validate.ts
  src/middleware.ts
  src/types/components/auth-form.ts
  src/types/components/edit-profile-form.ts
Labels: ✨ Feature, 📬 API, 🎨 HTML&CSS, 🐞 BugFix, 🔨 Refactor, 🌝 수임

#90 add:#89 install shadcn select
  package.json
  pnpm-lock.yaml
  src/components/ui/select.tsx
Labels: ⚙ Setting

#84 Feature/#69 마이페이지 _ 다음 레벨까지 남은 개수 구하는 로직 및 코드 리팩토링
  src/app/(auth)/mypage/achievement/page.tsx
  src/lib/utils/api/my-life.api.ts
  src/lib/utils/api/my-mission.api.ts
  src/lib/utils/get-level-by-types.ts
  src/lib/utils/parse-user-mission.ts
  src/types/my-missions.ts
Labels: ✨ Feature, 📬 API, 🔨 Refactor, 🥨 지은

#88 Feature/#80 gonggam board 기능구현
  src/app/gonggam/(board)/[category]/page.tsx
  src/app/gonggam/post/page.tsx
  src/components/features/gonggam/gonggam-header.tsx
  src/components/features/gonggam/gonggam-post-card.tsx
  src/constants/page-path.ts
  src/lib/utils/api/gonggam-board.api.ts
  src/lib/utils/date-format.ts
  src/lib/utils/utc-to-kst.ts
  src/types/gonggam.ts
  src/types/supabase.d.ts
Labels: ✨ Feature, 📬 API, 🍋 예린

#87 Feature/#73 delete modal
  src/components/common/edit-delete-dropdown.tsx
  src/components/features/modals/delete-confirm.tsx
Labels: ✨ Feature, 🐣 민주

#94 #77 input- ui 수정 및 edit page 추가
  src/app/(life)/life/page.tsx
  src/app/(life)/life/post/edit/[post_id]/page.tsx
  src/components/common/image-uploader.tsx
  src/components/common/post-input-form.tsx
  src/components/common/solo-life-card.tsx
  src/components/common/tag-input.tsx
  src/constants/query-keys.ts
  src/lib/hooks/mutations/use-life-posts.ts
  src/lib/hooks/mutations/use-update-life-post.ts
  src/lib/hooks/queries/use-life-posts-by-month-range.ts
  src/lib/hooks/queries/use-life-posts-by-month.ts
  src/lib/utils/api/life-api-client.ts
  src/lib/utils/api/my-life.api.ts
  src/lib/utils/parse-tags.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 🐈‍⬛ 선제

#97 Feature/#85 mypage gonggam 나의 공감 게시글 기능 구현 및 UI 작업
  src/app/(auth)/mypage/my-gonggam-post-list/page.tsx
  src/app/(auth)/mypage/my-life-list/page.tsx
  src/components/features/mypage/my-gonggam-filter.tsx
  src/components/features/mypage/my-gonggam-post-client.tsx
  src/components/features/mypage/mypage-gonggam-item-container.tsx
  src/components/features/mypage/mypage-gonggam-item.tsx
  src/components/ui/select.tsx
  src/constants/query-keys.ts
  src/constants/supabase-tables-name.ts
  src/lib/hooks/queries/use-get-gonggam-posts-infinite-query.ts
  src/lib/utils/api/my-gonggam-client.api.ts
  src/types/gonggam-posts.ts
  src/types/supabase.d.ts
Labels: ✨ Feature, 📬 API, 🎨 HTML&CSS, 🥨 지은

#101 Feature/#19 ramdom mission modal 리팩토링
  src/app/(auth)/mypage/achievement/page.tsx
  src/app/page.tsx
  src/components/features/home/main-random-mission-box.tsx
  src/components/features/modals/calendar-post-detail.tsx
  src/components/features/modals/random-mission.tsx
  src/components/features/mypage/button-client-component.tsx
  src/lib/hooks/queries/use-missions.ts
  src/lib/utils/api/mission-list.api.ts
  src/lib/utils/api/missions.api.ts
Labels: 📬 API, 🔨 Refactor, 🐣 민주

#103 Refactor/#99 회원관련 로직 리팩토링 및 버셀 라우트 핸들러 경로 설정
  src/app/(auth)/login/page.tsx
  src/app/(auth)/mypage/achievement/page.tsx
  src/app/(auth)/mypage/my-life-list/page.tsx
  src/app/(auth)/mypage/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(checklist)/checklist/[mission]/page.tsx
  src/app/(life)/life/page.tsx
  src/app/(life)/life/post/page.tsx
  src/app/api/auth/callback/route.ts
  src/app/api/auth/check-duplicate/route.ts
  src/app/api/auth/google/route.ts
  src/app/api/auth/kakao/route.ts
  src/app/api/auth/profile/route.ts
  src/app/api/auth/user-session-state/route.ts
  src/app/auth/confirm/route.ts
  src/app/page.tsx
  src/components/common/profile-avatar.tsx
  src/components/features/auth-form/auth-content.tsx
  src/components/features/auth-form/auth-form-field.tsx
  src/components/features/auth-form/auth-form.tsx
  src/components/features/auth-form/auth-page-ui.tsx
  src/components/features/auth-form/duplicate-check-message.tsx
  src/components/features/auth-form/login-form-button.tsx
  src/components/features/auth-form/login-form.tsx
  src/components/features/auth-form/signup-form-button.tsx
  src/components/features/auth-form/signup-form.tsx
  src/components/features/mypage/edit-profile-form-nickname-field.tsx
  src/components/features/mypage/edit-profile-form.tsx
  src/components/features/mypage/mypage-sidebar-profile.tsx
  src/components/features/mypage/mypage-sidebar.tsx
  src/components/layout/header/header-dropdown-menu-item.tsx
  src/components/layout/header/header-user-option.tsx
  src/components/layout/header/header.tsx
  src/components/ui/form.tsx
  src/constants/api-path.ts
  src/constants/api-url.ts
  src/constants/auth-form.ts
  src/constants/messages.ts
  src/lib/hooks/mutations/use-profile-update-mutate.ts
  src/lib/hooks/queries/use-get-user-profile.ts
  src/lib/hooks/use-auth-form.ts
  src/lib/hooks/use-login-form.ts
  src/lib/hooks/use-profile-form.ts
  src/lib/hooks/use-signup-form.ts
  src/lib/utils/api/auth-action.ts
  src/lib/utils/api/auth-client.api.ts
  src/lib/utils/api/auth.api.ts
  src/lib/utils/api/my-life-client.api.ts
  src/lib/utils/api/my-mission.api.ts
  src/lib/utils/api/update-user-profile.api.ts
  src/lib/utils/supabase/middleware.ts
  src/lib/utils/validation/auth-schema.ts
  src/types/components/auth-form.ts
Labels: 📬 API, 🌏 Deploy, 🔨 Refactor, 🌝 수임

#112 Chore:P-N Rule 자동 설치
  .github/workflows/pull-request-commenter.yml
Labels: ⚙ Setting, 🐣 민주

#116 Refactor/#98 gonggam item component 작성자 및 날짜 표기
  src/app/(auth)/mypage/my-gonggam-post-list/page.tsx
  src/components/features/mypage/my-gonggam-post-client.tsx
  src/components/features/mypage/mypage-gonggam-item.tsx
  src/lib/utils/api/my-gonggam-client.api.ts
  src/types/gonggam-posts.ts
Labels: 🔨 Refactor, 🥨 지은

#120 Bugfix/#118 pr 룰 삭제 및 템플릿 수정
  .github/pull_request_template.yml
  .github/workflows/pull-request-commenter.yml
Labels: ⚙ Setting

#123 Install/#122 date fns framer motion react swipeable
  package.json
  pnpm-lock.yaml
Labels: ⚙ Setting, 🐈‍⬛ 선제

#105 Feature/#104 메인페이지 이미지 적용
  public/images/main-character.svg
  public/images/갓생.svg
  public/images/청소.svg
  public/images/혼놀.svg
  public/images/혼밥.svg
  public/images/혼자여행.svg
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/features/home/main-banner-swiper.tsx
  src/components/features/home/main-banner.tsx
  src/components/features/home/main-checklist-card.tsx
  src/components/features/home/main-gonggam-item-container.tsx
  src/components/features/home/main-gonggam-preview-container.tsx
  src/components/features/home/main-gonggam-preview-list-container.tsx
  src/components/features/home/main-gonggam-preview-title-box.tsx
  src/components/features/home/main-gonggam-preview-title-section.tsx
  src/components/features/home/main-gonggam-preview.tsx
  src/components/features/home/main-random-mission-box.tsx
  src/components/features/home/main-random-mission-button.tsx
  src/components/features/home/main-random-mission-container.tsx
  src/components/features/home/main-random-mission-image.tsx
  src/components/features/home/main-random-mission.tsx
  src/components/features/home/main-random-title-box.tsx
  src/components/features/home/main-random-title.tsx
  src/constants/default-image-url.ts
  src/types/components/main-banner.ts
  src/types/supabase.d.ts
Labels: 🎨 HTML&CSS, 🌝 수임

#107 Feature/#106 공감 게시글 조회수 기능 구현
  src/app/api/view-count/[id]/route.ts
  src/components/features/home/main-gonggam-item.tsx
  src/components/features/home/main-gonggam-preview.tsx
  src/constants/api-path.ts
  src/constants/messages.ts
  src/lib/hooks/use-view-count.ts
  src/lib/utils/api/gonggam-board.api.ts
  src/lib/utils/api/gonggam-posts.api.ts
  src/lib/utils/api/gonggam-view-count.api.ts
  src/types/gonggam-posts.ts
  src/types/supabase.d.ts
  src/types/user.ts
Labels: ✨ Feature, 📬 API, 🌝 수임

#121 Feat /#111 calendar slide
  src/components/features/life/calendar.tsx
  src/components/features/life/calendar/calendar-cell.tsx
  src/components/features/life/calendar/calendar-header.tsx
  src/components/features/life/calendar/calendar-render-dot.tsx
  src/components/features/life/calendar/calendar-weekdays.tsx
  src/components/features/life/calendar/calendar.tsx
  src/components/features/life/life-page-client.tsx
  src/components/features/life/solo-life-list.tsx
  src/lib/hooks/mutations/use-life-posts.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 🐈‍⬛ 선제

#125 Refactor/#124 미들웨어 동적경로 추가
  src/lib/utils/supabase/middleware.ts
Labels: 🔨 Refactor, 🌝 수임

#132 Feature/#93 gonggam detail 기능 구현 중간PR
  src/app/gonggam/(post)/[category]/[postId]/page.tsx
  src/components/features/gonggam/gonggam-comment-form.tsx
  src/components/features/gonggam/gonggam-comment-list.tsx
  src/components/features/gonggam/gonggam-likes.tsx
  src/components/features/gonggam/gonggam-my-post-dropdown.tsx
  src/components/features/gonggam/gonggam-pagination.tsx
  src/constants/messages.ts
  src/constants/query-keys.ts
  src/lib/hooks/mutations/use-delete-gonggam-post.ts
  src/lib/hooks/mutations/use-gonggam-mutation.ts
  src/lib/hooks/queries/use-gonggam-comments.ts
  src/lib/utils/api/auth.api.ts
  src/lib/utils/api/checklist-post.api.ts
  src/lib/utils/api/checklist.api.ts
  src/lib/utils/api/gonggam-board.api.ts
  src/lib/utils/api/gonggam-detail-client.api.ts
  src/lib/utils/api/gonggam-detail.api.ts
  src/lib/utils/toast.ts
  src/lib/utils/utc-to-kst.ts
  src/types/checklist.ts
  src/types/gonggam.ts
  src/types/supabase.d.ts
Labels: ✨ Feature, 📬 API, 🍋 예린

#136 Refactor/#119 my achievement refactoring 디자인 반영
  public/images/chevron-right.svg
  public/images/clean-icon.svg
  public/images/goat-icon.svg
  public/images/meal-icon.svg
  public/images/play-icon.svg
  public/images/tooltip-box.svg
  public/images/travel-icon.svg
  src/app/(auth)/mypage/achievement/page.tsx
  src/components/features/mypage/button-client-component.tsx
  src/components/features/mypage/mypage-progressbar.tsx
Labels: 🎨 HTML&CSS, 🥨 지은

#141 Feature/#127 input form UI
  src/components/common/image-uploader.tsx
  src/components/common/tag-input.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, 🐈‍⬛ 선제

#138 Refactor/#135 header styling
  src/app/layout.tsx
  src/components/layout/header/header-dropdown-menu-item.tsx
  src/components/layout/header/header-dropdown-menu.tsx
  src/components/layout/header/header-guest-option.tsx
  src/components/layout/header/header-main-logo.tsx
  src/components/layout/header/header-nav-challenge-menu.tsx
  src/components/layout/header/header-nav-link-item.tsx
  src/components/layout/header/header-nav.tsx
  src/components/layout/header/header-user-option.tsx
  src/components/layout/header/header.tsx
  src/components/ui/custom-button.tsx
Labels: 🎨 HTML&CSS, 🌝 수임

#143 Refactor/#139 메인 페이지 디자인 반영
  src/app/globals.css
  src/app/page.tsx
  src/components/features/home/main-banner.tsx
  src/components/features/home/main-checklist-card.tsx
  src/components/features/home/main-gonggam-item-container.tsx
  src/components/features/home/main-gonggam-item-contents-container.tsx
  src/components/features/home/main-gonggam-item.tsx
  src/components/features/home/main-gonggam-preview-title-section.tsx
  src/components/features/home/main-random-mission-button.tsx
  src/components/features/home/main-random-mission.tsx
Labels: 🎨 HTML&CSS, 🌝 수임

#144 Refactor/#137 mypage design 마이페이지 디자인 시안 반영
  src/app/(auth)/mypage/achievement/page.tsx
  src/app/(auth)/mypage/layout.tsx
  src/app/(auth)/mypage/my-gonggam-post-list/page.tsx
  src/app/(auth)/mypage/my-life-list/page.tsx
  src/components/common/profile-avatar.tsx
  src/components/features/mypage/my-gonggam-filter.tsx
  src/components/features/mypage/my-gonggam-post-client.tsx
  src/components/features/mypage/my-life-list-client.tsx
  src/components/features/mypage/mypage-gonggam-item-container.tsx
  src/components/features/mypage/mypage-gonggam-item.tsx
  src/components/features/mypage/mypage-sidebar-profile.tsx
  src/components/features/mypage/mypage-sidebar.tsx
  src/components/ui/select.tsx
  src/lib/utils/api/my-gonggam-client.api.ts
Labels: 🎨 HTML&CSS, 🔨 Refactor, 🥨 지은

#147 Feat /#142 modal install
  src/components/common/post-input-form.tsx
  src/components/common/solo-life-card.tsx
  src/components/common/tag-input.tsx
  src/components/features/life/calendar/calendar-header.tsx
  src/components/features/life/calendar/calendar.tsx
  src/components/features/life/life-page-client.tsx
  src/components/features/life/solo-life-list.tsx
  src/components/features/modals/calendar-post-detail.tsx
  src/lib/hooks/mutations/use-update-life-post.ts
Labels: ✨ Feature, 🐈‍⬛ 선제

#146 Refactor/#145 로그인, 회원가입 페이지 디자인 반영
  public/images/google.svg
  public/images/kakao.svg
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/components/features/auth-form/auth-content.tsx
  src/components/features/auth-form/auth-form-field.tsx
  src/components/features/auth-form/login-form-button.tsx
  src/components/features/auth-form/login-form.tsx
  src/components/features/auth-form/signup-form-button.tsx
  src/components/features/home/main-banner.tsx
  src/components/features/home/main-random-mission-container.tsx
  src/components/features/home/main-random-mission.tsx
  src/components/features/home/main-random-title.tsx
  src/constants/default-image-url.ts
  src/constants/messages.ts
Labels: 🎨 HTML&CSS, 🌝 수임

#150 Bugfix/#149 svg warning fix
  public/images/challenge_menu.svg
  public/images/gonggam-preview.svg
  public/images/청소.svg
  public/images/혼자여행.svg
  src/components/features/home/main-banner.tsx
  src/components/features/home/main-checklist-card.tsx
  src/components/features/home/main-gonggam-preview-title-section.tsx
  src/components/layout/header/header-nav-challenge-menu.tsx
Labels: 🐞 BugFix, 🌝 수임

#151 Refactor/#140 checklist design with detail modal
  public/images/checklist-done.svg
  public/images/checklist-undo.svg
  src/app/(checklist)/checklist/[mission]/page.tsx
  src/components/features/checklist/checklist-client.tsx
  src/components/features/checklist/checklist-progress.tsx
  src/components/features/checklist/mission-list-client.tsx
  src/constants/messages.ts
  src/constants/query-keys.ts
  src/lib/hooks/queries/use-get-life-post-by-mission-id.ts
  src/lib/utils/api/life-by-mission.api.ts
  src/types/checklist.ts
Labels: 📬 API, 🎨 HTML&CSS, 🍋 예린

#154 Feature/#152 mypage modal 모달 설치 완료
  src/components/features/mypage/my-gonggam-post-client.tsx
  src/components/features/mypage/my-life-list-client.tsx
Labels: ✨ Feature, 🥨 지은

#155 Refactor/#137 edit profile page styling
  public/images/camera.svg
  src/app/(auth)/mypage/layout.tsx
  src/app/(auth)/mypage/page.tsx
  src/components/features/auth-form/auth-form-field.tsx
  src/components/features/auth-form/duplicate-check-message.tsx
  src/components/features/auth-form/login-form.tsx
  src/components/features/mypage/edit-profile-form-email-field.tsx
  src/components/features/mypage/edit-profile-form-image-field.tsx
  src/components/features/mypage/edit-profile-form-nickname-field.tsx
  src/components/features/mypage/edit-profile-form.tsx
  src/components/features/mypage/mypage-sidebar-profile.tsx
  src/components/features/mypage/mypage-sidebar.tsx
  src/components/features/mypage/profile-avatar.tsx
  src/components/ui/custom-button.tsx
  src/constants/messages.ts
Labels: 🎨 HTML&CSS, 🌝 수임

#157 Refactor/#156 에러페이지 디자인 반영
  src/app/error.tsx
  src/app/error/page.tsx
  src/app/not-found.tsx
  src/components/common/error-block.tsx
Labels: 🎨 HTML&CSS, 🌝 수임

#165 Refactor/#163 삭제 모달 디자인 반영
  src/components/features/modals/delete-confirm.tsx
Labels: 🎨 HTML&CSS, 🌝 수임

#166 Refactor/#161 gonggam styling 게시글 상세페이지 디자인 반영
  src/app/gonggam/(post)/[category]/[postId]/page.tsx
  src/components/features/gonggam/gonggam-image-swiper.tsx
  src/components/features/gonggam/gonggam-likes.tsx
Labels: 🎨 HTML&CSS, 🥨 지은

#158 feat:#102 수정 로직 완료 및 디자인 반영
  public/images/go-back-icon.svg
  src/app/gonggam/(post)/[category]/[postId]/page.tsx
  src/app/gonggam/post/edit/[postId]/page.tsx
  src/components/features/gonggam/gonggam-header.tsx
  src/components/features/gonggam/gonggam-my-post-dropdown.tsx
  src/components/features/gonggam/gonggam-post-input-form.tsx
  src/components/features/gonggam/gonggam-select-box.tsx
  src/constants/gonggam-category.ts
  src/lib/hooks/mutations/use-update-gonggam-post.ts
  src/middleware.ts
Labels: ✨ Feature, 📬 API, 🎨 HTML&CSS, 🐣 민주

#170 design:#161 이미지 fill 로 변경
  src/components/features/gonggam/gonggam-image-swiper.tsx
Labels: 🎨 HTML&CSS, 🥨 지은

#176 fix:#175 svg icon 콘솔 오류 픽스
  src/app/(auth)/mypage/achievement/page.tsx
Labels: 🐞 BugFix, 🥨 지은

#179 Feature/#172 gonggam detail 중간PR(조회수, 디자인적용)
  src/app/gonggam/(post)/[category]/[postId]/layout.tsx
  src/app/gonggam/(post)/[category]/[postId]/page.tsx
  src/components/features/gonggam/gonggam-board-meta.tsx
  src/components/features/gonggam/gonggam-comment-form.tsx
  src/components/features/gonggam/gonggam-comment-list.tsx
  src/components/features/gonggam/gonggam-detail-view-count.tsx
  src/components/features/gonggam/gonggam-post-card.tsx
  src/components/ui/custom-button.tsx
  src/lib/utils/api/gonggam-board-client.api.ts
  src/lib/utils/supabase/middleware.ts
Labels: ✨ Feature, 🍋 예린

#177 design:#173 디자인 적용
  src/components/common/date-picker.tsx
  src/components/common/post-input-form.tsx
Labels: 🎨 HTML&CSS, 🐈‍⬛ 선제

#191 Refactor/#190 gen types update
  .vscode/settings.json
  src/components/features/auth-form/login-form-button.tsx
  src/components/features/auth-form/signup-form-button.tsx
  src/components/features/gonggam/gonggam-post-input-form.tsx
  src/components/features/home/main-banner-swiper.tsx
  src/components/features/home/main-banner.tsx
  src/components/features/home/main-gonggam-item.tsx
  src/components/features/home/main-random-mission-button.tsx
  src/components/features/modals/random-mission.tsx
  src/components/features/mypage/button-client-component.tsx
  src/components/features/mypage/edit-profile-form-image-field.tsx
  src/components/features/mypage/edit-profile-form-nickname-field.tsx
  src/components/features/mypage/edit-profile-form.tsx
  src/components/features/mypage/my-gonggam-post-client.tsx
  src/components/features/mypage/mypage-gonggam-item.tsx
  src/components/features/mypage/mypage-sidebar-profile.tsx
  src/components/layout/header/header-dropdown-menu-item.tsx
  src/components/layout/header/header-dropdown-menu.tsx
  src/components/layout/header/header-nav-challenge-menu.tsx
  src/components/layout/header/header-user-option.tsx
  src/constants/query-keys.ts
  src/lib/hooks/queries/use-get-gonggam-posts-infinite-query.ts
  src/lib/hooks/queries/use-get-user-profile.ts
  src/lib/hooks/use-profile-form.ts
  src/lib/utils/api/auth-action.ts
  src/lib/utils/api/auth-client.api.ts
  src/lib/utils/api/auth.api.ts
  src/lib/utils/api/gonggam-board.api.ts
  src/lib/utils/api/missions.api.ts
  src/lib/utils/api/my-gonggam-client.api.ts
  src/lib/utils/api/profile-image-upload.api.ts
  src/types/auth-form.ts
  src/types/components/auth-form.ts
  src/types/components/edit-profile-form.ts
  src/types/gonggam-posts.ts
  src/types/gonggam.ts
  src/types/header.ts
  src/types/life-post.ts
  src/types/main-banner.ts
  src/types/my-missions.ts
  src/types/supabase-const.ts
  src/types/supabase.d.ts
Labels: ⚙ Setting, 🔨 Refactor, 🌝 수임

#189 refactor:#186 run lint로 발견한 에러 적용
  src/components/features/gonggam/gonggam-post-input-form.tsx
  src/components/features/modals/calendar-post-detail.tsx
  src/components/features/modals/delete-confirm.tsx
  src/components/features/modals/random-mission.tsx
Labels: 🔨 Refactor, 🐣 민주

#188 Bugfix/#185 mypage linting
  src/components/features/mypage/my-gonggam-post-client.tsx
  src/components/features/mypage/my-life-list-client.tsx
  src/components/features/mypage/mypage-progressbar.tsx
Labels: 🐞 BugFix, 🥨 지은

#195 refactor:#194 해쉬태그 입력 오류
  src/components/common/tag-input.tsx
Labels: 🐞 BugFix, 🔨 Refactor, 🐣 민주

#200 Feature/#172 gonggam detail MVP 구현 중간 PR
  src/app/(checklist)/checklist/[mission]/page.tsx
  src/app/(life)/life/post/page.tsx
  src/app/gonggam/(post)/[category]/[postId]/page.tsx
  src/components/common/post-input-form.tsx
  src/components/features/checklist/checklist-client.tsx
  src/components/features/checklist/checklist-post-dropdown.tsx
  src/components/features/checklist/checklist-progress.tsx
  src/components/features/checklist/mission-list-client.tsx
  src/components/features/gonggam/gonggam-comment-form.tsx
  src/components/features/gonggam/gonggam-comment-list.tsx
  src/components/features/gonggam/gonggam-likes.tsx
  src/components/features/gonggam/gonggam-my-post-dropdown.tsx
  src/components/features/gonggam/gonggam-pagination.tsx
  src/components/features/gonggam/gonggam-post-card.tsx
  src/components/ui/pagination.tsx
  src/constants/gonggam-category.ts
  src/constants/messages.ts
  src/lib/hooks/mutations/use-delete-gonggam-comment.ts
  src/lib/hooks/mutations/use-delete-gonggam-post.ts
  src/lib/utils/api/checklist/checklist-post.api.ts
  src/lib/utils/api/checklist/checklist.api.ts
  src/lib/utils/api/gonggam/gonggam-board.api.ts
  src/lib/utils/api/gonggam/gonggam-detail.api.ts
  src/types/checklist.ts
  src/types/gonggam.ts
Labels: ✨ Feature, 📬 API, 🍋 예린

#184 Bugfix/#182 code recovery
  src/components/common/post-input-form.tsx
  src/components/common/tag-input.tsx
  src/components/features/checklist/checklist-post-dropdown.tsx
  src/components/features/life/calendar/calendar-render-dot.tsx
  src/lib/hooks/queries/use-life-posts-by-month-range.ts
  src/lib/hooks/queries/use-life-posts-by-month.ts
  src/lib/utils/api/life/life-client.api.ts
Labels: 🔨 Refactor, 🐈‍⬛ 선제

#198 refactor:#197 edit-delete-dropdown 리팩토링
  src/components/common/edit-delete-dropdown.tsx
Labels: 🔨 Refactor, 🐣 민주

#196 Refactor/#187 header refactoring
  src/app/globals.css
  src/components/layout/header/header-dropdown-menu-item.tsx
  src/components/layout/header/header-dropdown-menu.tsx
  src/components/layout/header/header-guest-option.tsx
  src/components/layout/header/header-main-logo.tsx
  src/components/layout/header/header-nav-challenge-menu.tsx
  src/components/layout/header/header-nav-label.tsx
  src/components/layout/header/header-nav-link-item.tsx
  src/components/layout/header/header-nav-under-bar.tsx
  src/components/layout/header/header-nav.tsx
  src/components/layout/header/header-user-option.tsx
  src/components/layout/header/header.tsx
  src/types/header.ts
Labels: 🔨 Refactor, 🌝 수임

#203 Feature/#199 마이페이지 전체 남은 개수 로직 구현 및 디자인 변경 사항 반영
  public/images/cat-in-question-box.svg
  public/images/cat-no-records.svg
  src/app/(auth)/mypage/achievement/page.tsx
  src/components/features/mypage/button-client-component.tsx
  src/components/features/mypage/my-gonggam-post-client.tsx
  src/components/features/mypage/my-life-list-client.tsx
  src/components/features/mypage/mypage-no-records-box.tsx
  src/components/features/mypage/mypage-progressbar.tsx
  src/components/features/mypage/mypage-radom-mission-box.tsx
  src/lib/utils/api/mypage/my-gonggam-client.api.ts
  src/lib/utils/api/mypage/my-life-client.api.ts
  src/lib/utils/calculate-user-level.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 🔨 Refactor, 🥨 지은

#207 Refactor/#201 random mission modal design
  src/components/features/modals/random-mission-loading-spinner.tsx
  src/components/features/modals/random-mission.tsx
Labels: 🎨 HTML&CSS, 🔨 Refactor, 🐣 민주

#204 Feature/#172 gonggam detail 기능구현 최종
  src/components/features/gonggam/gonggam-comment-form.tsx
  src/components/features/gonggam/gonggam-comment-item.tsx
  src/components/features/gonggam/gonggam-comment-list.tsx
  src/components/features/gonggam/gonggam-likes.tsx
  src/constants/messages.ts
  src/lib/hooks/mutations/use-update-gonggam-comment.ts
Labels: ✨ Feature, 🍋 예린

#211 refactor:#208 모바일 디자인 반영 및 뒤로가기 적용
  src/components/features/modals/delete-confirm.tsx
Labels: 🎨 HTML&CSS, 🔨 Refactor, 🐣 민주

#213 Refactor/#206 mypage 모바일 디자인 중간PR
  src/app/(auth)/mypage/achievement/page.tsx
  src/app/(auth)/mypage/layout.tsx
  src/app/(auth)/mypage/my-gonggam-post-list/page.tsx
  src/app/(auth)/mypage/my-life-list/page.tsx
  src/components/features/mypage/my-gonggam-filter.tsx
  src/components/features/mypage/my-gonggam-post-client.tsx
  src/components/features/mypage/mypage-progressbar.tsx
  src/components/features/mypage/mypage-radom-mission-box.tsx
  src/components/features/mypage/mypage-sidebar-desktop.tsx
  src/components/features/mypage/mypage-sidebar-mobile.tsx
  src/components/features/mypage/mypage-sidebar-profile-desktop.tsx
  src/components/features/mypage/mypage-sidebar-profile-mobile.tsx
  src/components/features/mypage/profile-avatar.tsx
  src/constants/default-image-url.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 🔨 Refactor, 🥨 지은

#217 Refactor: confirm-modal
  src/components/common/edit-delete-dropdown.tsx
  src/components/common/post-input-form.tsx
  src/components/features/gonggam/gonggam-comment-list.tsx
  src/components/features/gonggam/gonggam-my-post-dropdown.tsx
  src/components/features/gonggam/gonggam-post-input-form.tsx
  src/components/features/modals/confirm-modal.tsx
Labels: 🔨 Refactor, 🐣 민주

#209 Feature /#202 input form css abst
  src/components/common/image-uploader.tsx
  src/components/common/post-input-form.tsx
  src/components/common/tag-input.tsx
  src/components/features/life/calendar/calendar-cell.tsx
  src/components/features/life/solo-life-list.tsx
  src/lib/hooks/queries/use-life-posts-by-month-range.ts
Labels: 🎨 HTML&CSS, 🔨 Refactor, 🐈‍⬛ 선제

#216 Refactor/#110 메인 페이지 변경사항 적용(중간pr)
  public/images/cat-in-question-box-original.svg
  public/images/footer-logo.svg
  public/images/main-banner-1.svg
  public/images/main-banner-2.svg
  public/images/main-banner-3.svg
  src/components/features/home/main-banner-image.tsx
  src/components/features/home/main-banner-swiper.tsx
  src/components/features/home/main-banner.tsx
  src/components/features/home/main-checklist-card-level.tsx
  src/components/features/home/main-checklist-card.tsx
  src/components/features/home/main-random-mission-image.tsx
  src/components/layout/footer/footer.tsx
  src/components/layout/header/header-main-logo.tsx
  src/components/ui/custom-button.tsx
  tailwind.config.ts
Labels: 🎨 HTML&CSS, 🔨 Refactor, 🌝 수임

#214 Refactor/#205 공감게시판 데이터 TanstackQuery 적용
  src/app/gonggam/(board)/[category]/page.tsx
  src/app/gonggam/(post)/[category]/[postId]/page.tsx
  src/components/features/gonggam/gonggam-comment-form.tsx
  src/components/features/gonggam/gonggam-comment-item.tsx
  src/components/features/gonggam/gonggam-detail-view-count.tsx
  src/components/features/gonggam/gonggam-image-swiper.tsx
  src/components/features/gonggam/gonggam-pagination.tsx
  src/components/features/gonggam/gonggam-post-card.tsx
  src/components/features/gonggam/gonggam-post-content.tsx
  src/components/ui/skeleton.tsx
  src/constants/query-keys.ts
  src/lib/hooks/mutations/use-delete-gonggam-comment.ts
  src/lib/hooks/mutations/use-delete-gonggam-post.ts
  src/lib/hooks/queries/use-get-gonggam-post-card-meta.ts
  src/lib/hooks/queries/use-get-gonggam-post-detail.ts
  src/lib/hooks/queries/use-paginated-gonggam-posts.ts
  src/lib/utils/api/gonggam/gonggam-board-client.api.ts
  src/lib/utils/api/gonggam/gonggam-board.api.ts
  src/lib/utils/api/gonggam/gonggam-detail-client.api.ts
  src/lib/utils/api/gonggam/gonggam-detail.api.ts
  src/types/gonggam.ts
Labels: 📬 API, 🐞 BugFix, 🍋 예린

#219 Refactor/#218 lint fix
  src/components/features/auth-form/auth-form-field.tsx
  src/components/features/mypage/edit-profile-form-nickname-field.tsx
Labels: 🐞 BugFix, 🔨 Refactor, 🌝 수임

#227 Install/#226 sheet 컴포넌트 설치
  package.json
  pnpm-lock.yaml
  src/components/ui/sheet.tsx
Labels: ⚙ Setting, 🌝 수임

#224 Refactor/#221 post detail modal
  src/components/common/edit-delete-dropdown.tsx
  src/components/features/modals/calendar-post-detail.tsx
  src/components/ui/card-detail-image-swiper.tsx
  tailwind.config.ts
Labels: 🎨 HTML&CSS, 🔨 Refactor, 🐣 민주

#235 파비콘 적용
  public/images/favicon.svg
  src/app/layout.tsx
Labels: 🎨 HTML&CSS, 🐣 민주

#233 Refactor/#228 user level refactoring
  src/lib/utils/get-level-by-types.ts
  src/lib/utils/parse-user-mission.ts
Labels: 🔨 Refactor, 🥨 지은

#242 Feature /#210 card UI change
  public/images/default-image.svg
  src/app/(life)/life/page.tsx
  src/components/common/no-records-box.tsx
  src/components/common/solo-life-card.tsx
  src/components/features/life/calendar/calendar-cell.tsx
  src/components/features/life/calendar/calendar-header.tsx
  src/components/features/life/calendar/calendar-render-dot.tsx
  src/components/features/life/calendar/calendar-weekdays.tsx
  src/components/features/life/calendar/calendar.tsx
  src/components/features/life/custom-header.tsx
  src/components/features/life/life-page-client.tsx
  src/components/features/life/solo-life-list.tsx
  src/lib/utils/utc-to-kst.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 🐈‍⬛ 선제

#236 Refactor/#220 고정 레이아웃 모바일 시안 반영
  public/images/header-mobile-menu-icon.svg
  src/app/globals.css
  src/app/layout.tsx
  src/components/layout/footer/footer.tsx
  src/components/layout/header/header-dropdown-menu-item.tsx
  src/components/layout/header/header-nav-challenge-menu-mobile.tsx
  src/components/layout/header/header-nav-challenge-menu.tsx
  src/components/layout/header/header-nav-label.tsx
  src/components/layout/header/header-nav-link-item-mobile.tsx
  src/components/layout/header/header-nav-link-item.tsx
  src/components/layout/header/header-nav-menu-mobile.tsx
  src/components/layout/header/header-nav.tsx
  src/components/layout/header/header-user-option.tsx
  src/components/layout/header/header.tsx
  src/contexts/pathname-context.tsx
Labels: 🎨 HTML&CSS, 🔨 Refactor, 🌝 수임

#243 Refactor/#241 마이페이지 시멘틱 태그 반영 및 QA 디자인 수정 반영
  src/app/(auth)/mypage/achievement/page.tsx
  src/app/(auth)/mypage/my-life-list/page.tsx
  src/components/features/mypage/my-gonggam-post-client.tsx
  src/components/features/mypage/my-life-list-client.tsx
  src/components/features/mypage/mypage-progressbar.tsx
  src/components/features/mypage/mypage-sidebar-desktop.tsx
  src/components/features/mypage/mypage-sidebar-profile-desktop.tsx
  src/components/features/mypage/mypage-sidebar-profile-mobile.tsx
  src/components/features/mypage/profile-avatar.tsx
Labels: 🎨 HTML&CSS, 🔨 Refactor, 🥨 지은

#244 Refactor/#225 checklist mobile 디자인 반영(swiper, QA)
  src/components/features/checklist/checklist-client.tsx
  src/components/features/checklist/checklist-mission-swiper.tsx
  src/components/features/checklist/checklist-progress.tsx
  src/components/features/checklist/mission-card-wrapper.tsx
  src/components/features/checklist/mission-card.tsx
  src/components/features/checklist/mission-list-client.tsx
Labels: 🎨 HTML&CSS, 🔨 Refactor, 🍋 예린

#250 Refactor/#249 auth page mobile styling
  src/components/features/auth-form/auth-content.tsx
  src/components/features/auth-form/login-form-button.tsx
  src/components/features/auth-form/login-form.tsx
  src/components/features/auth-form/signup-form-button.tsx
  src/components/features/auth-form/signup-form.tsx
Labels: 🎨 HTML&CSS, 🔨 Refactor, 🌝 수임

#252 Refactor/#251 error page mobile styling
  src/components/common/error-block.tsx
Labels: 🎨 HTML&CSS, 🔨 Refactor, 🌝 수임

#255 Refactor/#241 마이페이지 모바일 디자인 수정 사항 2곳 반영
  src/app/(auth)/mypage/achievement/page.tsx
  src/components/features/mypage/my-gonggam-post-client.tsx
Labels: 🎨 HTML&CSS, 🥨 지은

#256 Refactor/#245 checklist bugfix (UI 업데이트)
  src/app/(checklist)/checklist/[mission]/page.tsx
  src/components/common/post-input-form.tsx
  src/components/features/checklist/checklist-client.tsx
  src/components/features/checklist/mission-card-wrapper.tsx
  src/components/features/checklist/skeleton-checklist.tsx
  src/constants/query-keys.ts
  src/lib/hooks/queries/use-get-checklist-data.ts
  src/lib/utils/api/checklist/checklist-client.api.ts
  src/lib/utils/api/checklist/checklist.api.ts
Labels: 🎨 HTML&CSS, 🐞 BugFix, 🔨 Refactor, 🍋 예린

#258 Refactor/#240 gonggam post page design
  src/components/common/image-uploader.tsx
  src/components/common/tag-input.tsx
  src/components/features/gonggam/gonggam-post-input-form.tsx
  src/lib/hooks/use-is-mobile.ts
Labels: 🎨 HTML&CSS, 🔨 Refactor, 🐣 민주

#248 Refactor/#247 edit profile page refactoring
  package.json
  pnpm-lock.yaml
  src/app/(auth)/mypage/page.tsx
  src/app/api/convert-heic/route.ts
  src/components/features/mypage/edit-profile-form-email-field.tsx
  src/components/features/mypage/edit-profile-form-image-field.tsx
  src/components/features/mypage/edit-profile-form-nickname-field.tsx
  src/components/features/mypage/edit-profile-form.tsx
  src/components/features/mypage/edit-profile-mobile-back-button.tsx
  src/components/features/mypage/profile-avatar.tsx
  src/components/layout/header/header-dropdown-menu-item.tsx
  src/components/layout/header/header-nav-challenge-menu-mobile.tsx
  src/components/layout/header/header-nav-challenge-menu.tsx
  src/components/layout/header/header-nav-label.tsx
  src/components/layout/header/header-nav-link-item-mobile.tsx
  src/components/layout/header/header-nav-menu-mobile.tsx
  src/components/layout/header/header-user-option.tsx
  src/components/ui/custom-button.tsx
  src/constants/messages.ts
  src/lib/utils/api/heic-convert-image.api.ts
  src/lib/utils/api/mypage/profile-image-upload.api.ts
  src/lib/utils/processed-image.ts
  src/types/heic-convert.d.ts
Labels: 🎨 HTML&CSS, 🔨 Refactor, 🌝 수임

#260 Refactor/#259 ut fix minju
  src/app/layout.tsx
  src/components/common/edit-delete-dropdown.tsx
  src/components/common/post-input-form.tsx
  src/components/features/modals/calendar-post-detail.tsx
Labels: 🎨 HTML&CSS, 🔨 Refactor, 🐣 민주

#265 Feature/#264 card mode add
  src/components/common/solo-life-card.tsx
  src/components/features/life/calendar/calendar-header.tsx
  src/components/features/life/calendar/calendar-render-dot.tsx
  src/components/features/life/life-page-client.tsx
  src/components/features/life/solo-life-list.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, 🐈‍⬛ 선제

#262 Feature/#253 onboarding page 구현
  public/images/onboarding-cat.svg
  public/images/onboarding-checklist-card.svg
  public/images/onboarding-floating.svg
  public/images/onboarding-gonggam.svg
  public/images/onboarding-level.svg
  public/images/onboarding-life.svg
  public/images/onboarding-mission.svg
  public/images/onboarding-random-mission.svg
  public/images/onboarding-slide-icon.svg
  public/images/onboarding-title.svg
  src/app/api/auth/callback/route.ts
  src/app/home/page.tsx
  src/app/page.tsx
  src/components/features/onboarding/challenge-section.tsx
  src/components/features/onboarding/end-section.tsx
  src/components/features/onboarding/floating-button.tsx
  src/components/features/onboarding/gonggam-board-section.tsx
  src/components/features/onboarding/life-section.tsx
  src/components/features/onboarding/mission-section.tsx
  src/components/features/onboarding/random-mission-section.tsx
  src/components/features/onboarding/text-block.tsx
  src/components/features/onboarding/title-section.tsx
  src/components/layout/footer/footer.tsx
  src/constants/page-path.ts
  src/lib/utils/supabase/middleware.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 🌝 수임

#268 Refactor/#241 마이페이지 카드 컴포넌트 mode 적용
  src/components/common/solo-life-card.tsx
  src/components/features/mypage/my-life-list-client.tsx
Labels: 🎨 HTML&CSS, 🔨 Refactor, 🥨 지은

#271 시간 라이브러리 date-fns/tz 설치
  package.json
  pnpm-lock.yaml
Labels: ⚙ Setting, 🐣 민주

#273 Bugfix/#272 TQ Provider 재설정
  src/lib/providers/TQProvider.tsx
Labels: 🐞 BugFix, 🌝 수임

#277 Refactor/#241 마이페이지 CLEAR 디자인 반영 및 useEffect 삭제/ 개선
  src/app/(auth)/mypage/achievement/page.tsx
  src/components/common/no-records-box.tsx
  src/components/features/mypage/my-gonggam-post-client.tsx
  src/components/features/mypage/my-life-list-client.tsx
  src/lib/hooks/mutations/use-delete-life-post.ts
  src/lib/utils/get-level-by-types.ts
  tailwind.config.ts
Labels: 🎨 HTML&CSS, 🔨 Refactor, 🥨 지은

#281 Feature/#280 guest login
  src/components/features/auth-form/login-form-button.tsx
  src/components/features/mypage/edit-profile-form.tsx
  src/components/features/mypage/mypage-sidebar-profile-desktop.tsx
  src/components/features/mypage/mypage-sidebar-profile-mobile.tsx
  src/lib/utils/api/auth/auth-action.ts
  src/lib/utils/api/auth/auth.api.ts
Labels: ✨ Feature, 🌝 수임

#275 Feature/#267 skeleton UI
  src/app/gonggam/(board)/[category]/layout.tsx
  src/app/gonggam/(board)/[category]/page.tsx
  src/components/common/post-input-form.tsx
  src/components/features/gonggam/gonggam-post-card.tsx
  src/components/features/gonggam/gonggam-post-content.tsx
  src/components/features/life/calendar/calendar.tsx
  src/components/features/life/life-page-client.tsx
  src/components/ui/skeleton.tsx
Labels: 🎨 HTML&CSS, 🐈‍⬛ 선제

#283 Feature/#279 mypage & calendar 스켈레톤 UI
  src/components/features/life/solo-life-list.tsx
  src/components/features/mypage/my-life-list-client.tsx
  src/components/ui/skeleton.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, 🥨 지은

#284 Refactor/#278 checklist design
  src/app/(checklist)/checklist/[mission]/page.tsx
  src/components/features/auth-form/login-form-button.tsx
  src/components/features/checklist/checklist-client.tsx
  src/components/features/checklist/checklist-mission-swiper.tsx
  src/components/features/checklist/checklist-progress.tsx
  src/components/features/checklist/mission-list-client.tsx
  src/lib/hooks/mutations/use-delete-gonggam-post.ts
  src/types/supabase.d.ts
  tailwind.config.ts
Labels: 🎨 HTML&CSS, 🔨 Refactor, 🍋 예린

#288 refactor/#287 미들웨어 리팩토링
  src/lib/utils/supabase/middleware.ts
Labels: 🐞 BugFix, 🔨 Refactor, 🌝 수임

#292 Feature/#279 my gonggam skeleton UI
  src/components/features/home/main-gonggam-item-contents-container.tsx
  src/components/features/mypage/my-gonggam-post-client.tsx
  src/components/features/mypage/mypage-gonggam-item.tsx
  src/components/ui/skeleton.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, 🥨 지은

#286 Refactor/#274 회원 관리 로직 리팩토링
  next.config.js
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/api/auth/check-duplicate/route.ts
  src/app/api/auth/google/route.ts
  src/app/api/auth/kakao/route.ts
  src/components/features/auth-form/auth-form-field.tsx
  src/components/features/auth-form/login-form-button.tsx
  src/components/features/auth-form/login-form.tsx
  src/components/features/auth-form/signup-form-button.tsx
  src/components/features/auth-form/signup-form.tsx
  src/components/features/mypage/edit-profile-form-email-field.tsx
  src/components/features/mypage/edit-profile-form-nickname-field.tsx
  src/components/features/mypage/edit-profile-form.tsx
  src/components/features/mypage/mypage-sidebar-profile-desktop.tsx
  src/components/features/mypage/mypage-sidebar-profile-mobile.tsx
  src/constants/auth-form.ts
  src/lib/hooks/use-login-form.ts
  src/lib/hooks/use-profile-form.ts
  src/lib/hooks/use-signup-form.ts
  src/lib/utils/api/auth/auth-action.ts
  src/lib/utils/api/auth/auth.api.ts
  src/types/auth-form.ts
Labels: 🔨 Refactor, 🌝 수임

#291 Feature #290 life page ssr
  src/app/(life)/life/page.tsx
  src/components/features/life/calendar/calendar-header.tsx
  src/components/features/life/life-page-client.tsx
  src/lib/hooks/queries/use-life-posts-by-month-range.ts
  src/lib/utils/api/life/life-server-api.ts
Labels: ✨ Feature, 🐈‍⬛ 선제

#294 Refactor/#259 ut fix minju 2차
  src/components/common/edit-delete-dropdown.tsx
  src/components/common/post-input-form.tsx
  src/components/common/tag-input.tsx
  src/components/features/modals/calendar-post-detail.tsx
  src/components/features/modals/random-mission.tsx
  src/lib/hooks/mutations/use-update-gonggam-post.ts
  src/lib/utils/utc-to-kst.ts
Labels: 🎨 HTML&CSS, 🐞 BugFix, 🔨 Refactor, 🐣 민주
