Repository taechoma-eul/YOLA, pull requests merged in 2025-05, with the labels that each got.

#296 Refactor/#289 유저테스트 피드백 반영
  next.config.js
  src/app/layout.tsx
  src/components/layout/header/header-nav-challenge-menu.tsx
  src/components/layout/header/header-user-option.tsx
  src/components/layout/header/header.tsx
Labels: 🔨 Refactor, 🌝 수임

#298 Refactor/#263 온보딩 페이지 모바일 시안 반영
  public/images/onboarding-gonggam-mobile.svg
  public/images/onboarding-level-mobile.svg
  public/images/onboarding-life-mobile.svg
  public/images/onboarding-mission-mobile.svg
  public/images/onboarding-random-mission-mobile.svg
  public/images/onboarding-title-mobile.svg
  src/app/page.tsx
  src/components/features/onboarding/challenge-section.tsx
  src/components/features/onboarding/end-section.tsx
  src/components/features/onboarding/gonggam-board-section.tsx
  src/components/features/onboarding/life-section.tsx
  src/components/features/onboarding/mission-section.tsx
  src/components/features/onboarding/random-mission-section.tsx
  src/components/features/onboarding/text-block.tsx
  src/components/features/onboarding/title-section.tsx
Labels: 🎨 HTML&CSS, 🔨 Refactor, 🌝 수임

#295 Docs/#293 readme
  README.md
  public/images/brochure.svg
  public/images/system-architecture.png
  public/images/team-members.png
  public/images/ui-flow.png
Labels: 📃 Docs, 🥨 지은

#297 Refactor/#285 checklist mobile bugfix (moblie, unmatched header)
  src/components/features/checklist/checklist-client.tsx
  src/components/features/checklist/checklist-progress.tsx
Labels: 🎨 HTML&CSS, 🐞 BugFix, 🍋 예린

#302 design:#301 ui 이슈 수정
  src/components/common/solo-life-card.tsx
Labels: 🎨 HTML&CSS, 🐈‍⬛ 선제
